version: '3.9'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             gunicorn django_jwt_auth.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
